[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --workspace app --omit=dev"
]

[phases.build]
cmds = [
  "cd app && npm run build"
]

[start]
cmd = "cd app && npm start"

[variables]
NODE_ENV = "production"
